### ISSUE TITLE
Requirements list?  

### ISSUE THREAD

**Issue by ScottTheHippy** [veebch/bullion#7]
Howdy Veebch,  I sure hope you don't get sick of hearing from me- I really like what you've been building and am trying to get them rolling.   With regard to this project, I've done the usual preamble of installs and configs, and saw some errors when getting to the requirements list install.  (two images attached) 
![Screen Shot 2024-02-24 at 4 49 18 PM](https://github.com/veebch/bullion/assets/101391563/59773d57-07e6-4a94-91a5-e76bb549070d)
![Screen Shot 2024-02-24 at 4 49 35 PM](https://github.com/veebch/bullion/assets/101391563/dcfe56d9-b388-4eb7-8b5e-efded2d49a9b)

I wasn't sure if those were show stoppers so I tried to run bullion.py with only three items in the list, and that led to an error message from 12data about too many queries on my API key,  so I dropped that down to just one and now see this error.  
![Screen Shot 2024-02-24 at 5 08 36 PM](https://github.com/veebch/bullion/assets/101391563/a8ed6cc9-8169-41f4-beef-c05b0624462a)
 I also don't see any signs of life or change on the e-paper screen.  Might that be connected to the issue with edify?  I'm happy to test however you like.  Would it be helpful or welcome to ship you a V2 of this Waveshare hat?  You know- for the cause?  :)

Cheers!

**Comment by veebch** [comment]
That's a bug! Fixed now.... 
No need to send a V2 screen..... I've got one knocking around somewhere  :)

**Comment by ScottTheHippy** [comment]
Howdy Veebch, about how long would you expect this to sit like this on a Pi Zero 2 W?   It's been a few min and I think I might be stalled.  I rm'ed the /bullion directory and picked back up from the repo cloning step, and edited the config.yaml again to my time zone (America/Los_Angeles) added my 12data key, and shortened the metals list to gold, silver, and platinum.  Still no signs of life on the screen and the script *seems* stuck.   Should I nuke the SD card from space and start fresh?  :)   Cheers!

**Comment by ScottTheHippy** [comment]
(forgot the image)  
![Screen Shot 2024-02-25 at 10 22 11 PM](https://github.com/veebch/bullion/assets/101391563/cc1eb830-1347-44cc-a8eb-0899a7b41f6b)

**Comment by ScottTheHippy** [comment]
More info: I wandered off 
![Screen Shot 2024-02-25 at 10 37 10 PM](https://github.com/veebch/bullion/assets/101391563/2d87bd50-4067-4fa6-b09d-8e93e19e918e)
for a spell and when I came back I could see at the prompt it's stepping through the metals I'd left in the list, but still nowhere with the display.  Any suggestions?   Cheers!

**Comment by ScottTheHippy** [comment]
ALMOST!   Howdy again Veebch, I made a minor breakthrough- I was perplexed by why I still get no signs of life with the bullion.py, but I can make things happen with the waveshare demo and eventually was looking at the code in bullion.py carefully.  There are two occasions where "epd2in7" are present, and in my case (and probably anyone else with a newer 2.7" epaper hat) I need "epd2in7_V2".   Now, having gotten that far I can see signs of life, but I'm faced with a gray on gray image problem where I can hardly see the data.   I'll have a whack at that next.   Cheers!

**Comment by ScottTheHippy** [comment]
Howdy Veebch- all sorted.  I haven't been able to reproduce the gray-on-gray deal since a reboot, so you can close this one.  Thanks as ever.   I'll try to sort out where things are on my end with edify.py tomorrow, thought I suspect it's the same situation with the "epd2in7_V2.py" need in the code.  You rock!

**Comment by veebch** [comment]
Congrats! It looks like you fixed it all as I slept :)
